# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'data_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(901, 609)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 901, 561))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tabWidget_2 = QtWidgets.QTabWidget(self.tab)
        self.tabWidget_2.setGeometry(QtCore.QRect(0, 0, 881, 531))
        self.tabWidget_2.setObjectName("tabWidget_2")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.label = QtWidgets.QLabel(self.tab_5)
        self.label.setGeometry(QtCore.QRect(110, 80, 72, 15))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.tab_5)
        self.pushButton.setGeometry(QtCore.QRect(50, 30, 121, 28))
        self.pushButton.setObjectName("pushButton")
        self.comboBox = QtWidgets.QComboBox(self.tab_5)
        self.comboBox.setGeometry(QtCore.QRect(260, 80, 141, 22))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.label_2 = QtWidgets.QLabel(self.tab_5)
        self.label_2.setGeometry(QtCore.QRect(60, 150, 72, 15))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit.setGeometry(QtCore.QRect(160, 150, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.tab_5)
        self.label_3.setGeometry(QtCore.QRect(330, 150, 72, 15))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_2.setGeometry(QtCore.QRect(430, 150, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setGeometry(QtCore.QRect(580, 150, 41, 16))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_3.setGeometry(QtCore.QRect(650, 150, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.tab_5)
        self.label_5.setGeometry(QtCore.QRect(150, 230, 91, 16))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_4.setGeometry(QtCore.QRect(270, 230, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.tab_5)
        self.label_6.setGeometry(QtCore.QRect(450, 230, 81, 16))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_5.setGeometry(QtCore.QRect(570, 230, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.tab_5)
        self.label_7.setGeometry(QtCore.QRect(150, 290, 101, 16))
        self.label_7.setObjectName("label_7")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_6.setGeometry(QtCore.QRect(270, 290, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_8 = QtWidgets.QLabel(self.tab_5)
        self.label_8.setGeometry(QtCore.QRect(450, 290, 91, 16))
        self.label_8.setObjectName("label_8")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.tab_5)
        self.lineEdit_7.setGeometry(QtCore.QRect(570, 290, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_5)
        self.pushButton_2.setGeometry(QtCore.QRect(390, 320, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_9 = QtWidgets.QLabel(self.tab_5)
        self.label_9.setGeometry(QtCore.QRect(390, 360, 101, 16))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_5)
        self.label_10.setGeometry(QtCore.QRect(340, 390, 241, 16))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_5)
        self.label_11.setGeometry(QtCore.QRect(340, 420, 181, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.tab_5)
        self.label_12.setGeometry(QtCore.QRect(330, 450, 201, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_5)
        self.label_13.setGeometry(QtCore.QRect(330, 480, 221, 16))
        self.label_13.setObjectName("label_13")
        self.tabWidget_2.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.pushButton_3 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_3.setGeometry(QtCore.QRect(60, 10, 111, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.radioButton = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton.setGeometry(QtCore.QRect(120, 50, 115, 19))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_6)
        self.radioButton_2.setGeometry(QtCore.QRect(560, 50, 115, 19))
        self.radioButton_2.setObjectName("radioButton_2")
        self.label_14 = QtWidgets.QLabel(self.tab_6)
        self.label_14.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_14.setObjectName("label_14")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_8.setGeometry(QtCore.QRect(90, 80, 71, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.label_16 = QtWidgets.QLabel(self.tab_6)
        self.label_16.setGeometry(QtCore.QRect(200, 80, 31, 16))
        self.label_16.setObjectName("label_16")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_10.setGeometry(QtCore.QRect(240, 80, 61, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.label_17 = QtWidgets.QLabel(self.tab_6)
        self.label_17.setGeometry(QtCore.QRect(50, 110, 61, 16))
        self.label_17.setObjectName("label_17")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_11.setGeometry(QtCore.QRect(110, 110, 71, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.label_18 = QtWidgets.QLabel(self.tab_6)
        self.label_18.setGeometry(QtCore.QRect(10, 140, 31, 16))
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.tab_6)
        self.label_19.setGeometry(QtCore.QRect(70, 140, 41, 16))
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.tab_6)
        self.label_20.setGeometry(QtCore.QRect(140, 140, 41, 16))
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.tab_6)
        self.label_21.setGeometry(QtCore.QRect(210, 140, 41, 16))
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.tab_6)
        self.label_22.setGeometry(QtCore.QRect(290, 140, 41, 16))
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.tab_6)
        self.label_23.setGeometry(QtCore.QRect(370, 140, 41, 16))
        self.label_23.setObjectName("label_23")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_12.setGeometry(QtCore.QRect(0, 160, 51, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_13.setGeometry(QtCore.QRect(60, 160, 51, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.lineEdit_14 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_14.setGeometry(QtCore.QRect(130, 160, 51, 21))
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.lineEdit_15 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_15.setGeometry(QtCore.QRect(200, 160, 51, 21))
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.lineEdit_16 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_16.setGeometry(QtCore.QRect(280, 160, 51, 21))
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_17.setGeometry(QtCore.QRect(360, 160, 51, 21))
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.tableView = QtWidgets.QTableView(self.tab_6)
        self.tableView.setGeometry(QtCore.QRect(0, 190, 421, 91))
        self.tableView.setObjectName("tableView")
        self.pushButton_4 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_4.setGeometry(QtCore.QRect(80, 290, 93, 28))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 290, 93, 28))
        self.pushButton_5.setObjectName("pushButton_5")
        self.label_24 = QtWidgets.QLabel(self.tab_6)
        self.label_24.setGeometry(QtCore.QRect(30, 330, 72, 15))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.tab_6)
        self.label_25.setGeometry(QtCore.QRect(160, 330, 72, 15))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.tab_6)
        self.label_26.setGeometry(QtCore.QRect(290, 330, 72, 15))
        self.label_26.setObjectName("label_26")
        self.comboBox_2 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_2.setGeometry(QtCore.QRect(10, 350, 87, 22))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.lineEdit_18 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_18.setGeometry(QtCore.QRect(130, 350, 113, 21))
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.lineEdit_19 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_19.setGeometry(QtCore.QRect(270, 350, 113, 21))
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.tableView_2 = QtWidgets.QTableView(self.tab_6)
        self.tableView_2.setGeometry(QtCore.QRect(0, 380, 431, 91))
        self.tableView_2.setObjectName("tableView_2")
        self.pushButton_6 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_6.setGeometry(QtCore.QRect(50, 470, 93, 28))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_7.setGeometry(QtCore.QRect(210, 470, 93, 28))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_8.setGeometry(QtCore.QRect(530, 290, 93, 28))
        self.pushButton_8.setObjectName("pushButton_8")
        self.lineEdit_20 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_20.setGeometry(QtCore.QRect(800, 80, 61, 21))
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.label_27 = QtWidgets.QLabel(self.tab_6)
        self.label_27.setGeometry(QtCore.QRect(460, 140, 41, 16))
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.tab_6)
        self.label_28.setGeometry(QtCore.QRect(460, 80, 81, 16))
        self.label_28.setObjectName("label_28")
        self.lineEdit_21 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_21.setGeometry(QtCore.QRect(560, 110, 71, 21))
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.label_29 = QtWidgets.QLabel(self.tab_6)
        self.label_29.setGeometry(QtCore.QRect(590, 140, 41, 16))
        self.label_29.setObjectName("label_29")
        self.lineEdit_22 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_22.setGeometry(QtCore.QRect(540, 80, 71, 21))
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.lineEdit_23 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_23.setGeometry(QtCore.QRect(700, 80, 61, 21))
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.label_30 = QtWidgets.QLabel(self.tab_6)
        self.label_30.setGeometry(QtCore.QRect(620, 80, 81, 16))
        self.label_30.setObjectName("label_30")
        self.lineEdit_24 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_24.setGeometry(QtCore.QRect(580, 160, 61, 21))
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_25.setGeometry(QtCore.QRect(450, 160, 61, 21))
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.lineEdit_26 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_26.setGeometry(QtCore.QRect(700, 160, 61, 21))
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.label_31 = QtWidgets.QLabel(self.tab_6)
        self.label_31.setGeometry(QtCore.QRect(710, 140, 41, 16))
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.tab_6)
        self.label_32.setGeometry(QtCore.QRect(500, 110, 61, 16))
        self.label_32.setObjectName("label_32")
        self.pushButton_9 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_9.setGeometry(QtCore.QRect(690, 290, 93, 28))
        self.pushButton_9.setObjectName("pushButton_9")
        self.label_33 = QtWidgets.QLabel(self.tab_6)
        self.label_33.setGeometry(QtCore.QRect(770, 80, 31, 16))
        self.label_33.setObjectName("label_33")
        self.tableView_3 = QtWidgets.QTableView(self.tab_6)
        self.tableView_3.setGeometry(QtCore.QRect(450, 190, 421, 91))
        self.tableView_3.setObjectName("tableView_3")
        self.label_34 = QtWidgets.QLabel(self.tab_6)
        self.label_34.setGeometry(QtCore.QRect(820, 140, 41, 16))
        self.label_34.setObjectName("label_34")
        self.lineEdit_27 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_27.setGeometry(QtCore.QRect(810, 160, 51, 21))
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.lineEdit_28 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_28.setGeometry(QtCore.QRect(742, 350, 81, 21))
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.pushButton_10 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_10.setGeometry(QtCore.QRect(730, 470, 93, 28))
        self.pushButton_10.setObjectName("pushButton_10")
        self.lineEdit_29 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_29.setGeometry(QtCore.QRect(660, 350, 61, 21))
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.label_35 = QtWidgets.QLabel(self.tab_6)
        self.label_35.setGeometry(QtCore.QRect(490, 330, 72, 15))
        self.label_35.setObjectName("label_35")
        self.pushButton_11 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_11.setGeometry(QtCore.QRect(560, 470, 93, 28))
        self.pushButton_11.setObjectName("pushButton_11")
        self.comboBox_3 = QtWidgets.QComboBox(self.tab_6)
        self.comboBox_3.setGeometry(QtCore.QRect(470, 350, 87, 22))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.label_36 = QtWidgets.QLabel(self.tab_6)
        self.label_36.setGeometry(QtCore.QRect(668, 330, 51, 16))
        self.label_36.setObjectName("label_36")
        self.tableView_4 = QtWidgets.QTableView(self.tab_6)
        self.tableView_4.setGeometry(QtCore.QRect(460, 380, 411, 91))
        self.tableView_4.setObjectName("tableView_4")
        self.label_37 = QtWidgets.QLabel(self.tab_6)
        self.label_37.setGeometry(QtCore.QRect(750, 330, 72, 15))
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_6)
        self.label_38.setGeometry(QtCore.QRect(580, 330, 61, 16))
        self.label_38.setObjectName("label_38")
        self.lineEdit_30 = QtWidgets.QLineEdit(self.tab_6)
        self.lineEdit_30.setGeometry(QtCore.QRect(580, 350, 61, 21))
        self.lineEdit_30.setText("")
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.pushButton_12 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_12.setGeometry(QtCore.QRect(350, 470, 93, 28))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_25 = QtWidgets.QPushButton(self.tab_6)
        self.pushButton_25.setGeometry(QtCore.QRect(450, 470, 93, 28))
        self.pushButton_25.setObjectName("pushButton_25")
        self.tabWidget_2.addTab(self.tab_6, "")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tabWidget_3 = QtWidgets.QTabWidget(self.tab_2)
        self.tabWidget_3.setGeometry(QtCore.QRect(0, 0, 881, 521))
        self.tabWidget_3.setObjectName("tabWidget_3")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.pushButton_26 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_26.setGeometry(QtCore.QRect(30, 10, 111, 28))
        self.pushButton_26.setObjectName("pushButton_26")
        self.label_77 = QtWidgets.QLabel(self.tab_7)
        self.label_77.setGeometry(QtCore.QRect(170, 50, 72, 15))
        self.label_77.setObjectName("label_77")
        self.lineEdit_61 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_61.setGeometry(QtCore.QRect(270, 50, 113, 21))
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.label_78 = QtWidgets.QLabel(self.tab_7)
        self.label_78.setGeometry(QtCore.QRect(160, 80, 72, 15))
        self.label_78.setObjectName("label_78")
        self.radioButton_5 = QtWidgets.QRadioButton(self.tab_7)
        self.radioButton_5.setGeometry(QtCore.QRect(210, 80, 61, 19))
        self.radioButton_5.setObjectName("radioButton_5")
        self.radioButton_6 = QtWidgets.QRadioButton(self.tab_7)
        self.radioButton_6.setGeometry(QtCore.QRect(280, 80, 61, 19))
        self.radioButton_6.setObjectName("radioButton_6")
        self.label_79 = QtWidgets.QLabel(self.tab_7)
        self.label_79.setGeometry(QtCore.QRect(180, 110, 41, 16))
        self.label_79.setObjectName("label_79")
        self.label_80 = QtWidgets.QLabel(self.tab_7)
        self.label_80.setGeometry(QtCore.QRect(170, 140, 72, 15))
        self.label_80.setObjectName("label_80")
        self.label_81 = QtWidgets.QLabel(self.tab_7)
        self.label_81.setGeometry(QtCore.QRect(150, 170, 91, 16))
        self.label_81.setObjectName("label_81")
        self.label_82 = QtWidgets.QLabel(self.tab_7)
        self.label_82.setGeometry(QtCore.QRect(150, 200, 91, 16))
        self.label_82.setObjectName("label_82")
        self.label_83 = QtWidgets.QLabel(self.tab_7)
        self.label_83.setGeometry(QtCore.QRect(150, 230, 91, 16))
        self.label_83.setObjectName("label_83")
        self.label_84 = QtWidgets.QLabel(self.tab_7)
        self.label_84.setGeometry(QtCore.QRect(111, 260, 121, 20))
        self.label_84.setObjectName("label_84")
        self.label_85 = QtWidgets.QLabel(self.tab_7)
        self.label_85.setGeometry(QtCore.QRect(170, 290, 51, 16))
        self.label_85.setObjectName("label_85")
        self.lineEdit_62 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_62.setGeometry(QtCore.QRect(270, 110, 113, 21))
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.lineEdit_63 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_63.setGeometry(QtCore.QRect(270, 140, 113, 21))
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.lineEdit_64 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_64.setGeometry(QtCore.QRect(270, 170, 113, 21))
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.lineEdit_65 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_65.setGeometry(QtCore.QRect(270, 200, 113, 21))
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.lineEdit_66 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_66.setGeometry(QtCore.QRect(270, 230, 113, 21))
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.lineEdit_67 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_67.setGeometry(QtCore.QRect(270, 260, 113, 21))
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.lineEdit_68 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_68.setGeometry(QtCore.QRect(270, 290, 113, 21))
        self.lineEdit_68.setObjectName("lineEdit_68")
        self.label_86 = QtWidgets.QLabel(self.tab_7)
        self.label_86.setGeometry(QtCore.QRect(530, 130, 101, 16))
        self.label_86.setObjectName("label_86")
        self.label_87 = QtWidgets.QLabel(self.tab_7)
        self.label_87.setGeometry(QtCore.QRect(501, 160, 101, 20))
        self.label_87.setObjectName("label_87")
        self.label_88 = QtWidgets.QLabel(self.tab_7)
        self.label_88.setGeometry(QtCore.QRect(500, 190, 91, 16))
        self.label_88.setObjectName("label_88")
        self.label_89 = QtWidgets.QLabel(self.tab_7)
        self.label_89.setGeometry(QtCore.QRect(500, 210, 91, 16))
        self.label_89.setObjectName("label_89")
        self.label_90 = QtWidgets.QLabel(self.tab_7)
        self.label_90.setGeometry(QtCore.QRect(510, 240, 81, 16))
        self.label_90.setObjectName("label_90")
        self.label_91 = QtWidgets.QLabel(self.tab_7)
        self.label_91.setGeometry(QtCore.QRect(500, 270, 111, 16))
        self.label_91.setObjectName("label_91")
        self.lineEdit_69 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_69.setGeometry(QtCore.QRect(640, 160, 113, 21))
        self.lineEdit_69.setObjectName("lineEdit_69")
        self.lineEdit_70 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_70.setGeometry(QtCore.QRect(640, 200, 113, 21))
        self.lineEdit_70.setObjectName("lineEdit_70")
        self.lineEdit_71 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_71.setGeometry(QtCore.QRect(640, 240, 113, 21))
        self.lineEdit_71.setObjectName("lineEdit_71")
        self.lineEdit_72 = QtWidgets.QLineEdit(self.tab_7)
        self.lineEdit_72.setGeometry(QtCore.QRect(640, 270, 113, 21))
        self.lineEdit_72.setObjectName("lineEdit_72")
        self.pushButton_27 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_27.setGeometry(QtCore.QRect(330, 330, 93, 28))
        self.pushButton_27.setObjectName("pushButton_27")
        self.pushButton_28 = QtWidgets.QPushButton(self.tab_7)
        self.pushButton_28.setGeometry(QtCore.QRect(470, 330, 93, 28))
        self.pushButton_28.setObjectName("pushButton_28")
        self.tableView_9 = QtWidgets.QTableView(self.tab_7)
        self.tableView_9.setGeometry(QtCore.QRect(40, 360, 821, 121))
        self.tableView_9.setObjectName("tableView_9")
        self.tabWidget_3.addTab(self.tab_7, "")
        self.tab_8 = QtWidgets.QWidget()
        self.tab_8.setObjectName("tab_8")
        self.pushButton_29 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_29.setGeometry(QtCore.QRect(20, 10, 93, 28))
        self.pushButton_29.setObjectName("pushButton_29")
        self.label_93 = QtWidgets.QLabel(self.tab_8)
        self.label_93.setGeometry(QtCore.QRect(390, 40, 72, 15))
        self.label_93.setObjectName("label_93")
        self.lineEdit_76 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_76.setGeometry(QtCore.QRect(370, 60, 91, 21))
        self.lineEdit_76.setObjectName("lineEdit_76")
        self.lineEdit_77 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_77.setGeometry(QtCore.QRect(370, 90, 91, 21))
        self.lineEdit_77.setObjectName("lineEdit_77")
        self.lineEdit_78 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_78.setGeometry(QtCore.QRect(370, 120, 91, 21))
        self.lineEdit_78.setObjectName("lineEdit_78")
        self.label_94 = QtWidgets.QLabel(self.tab_8)
        self.label_94.setGeometry(QtCore.QRect(231, 60, 111, 20))
        self.label_94.setObjectName("label_94")
        self.label_95 = QtWidgets.QLabel(self.tab_8)
        self.label_95.setGeometry(QtCore.QRect(231, 90, 111, 20))
        self.label_95.setObjectName("label_95")
        self.label_96 = QtWidgets.QLabel(self.tab_8)
        self.label_96.setGeometry(QtCore.QRect(261, 120, 91, 20))
        self.label_96.setObjectName("label_96")
        self.label_97 = QtWidgets.QLabel(self.tab_8)
        self.label_97.setGeometry(QtCore.QRect(40, 150, 161, 16))
        self.label_97.setObjectName("label_97")
        self.label_98 = QtWidgets.QLabel(self.tab_8)
        self.label_98.setGeometry(QtCore.QRect(30, 180, 72, 15))
        self.label_98.setObjectName("label_98")
        self.label_99 = QtWidgets.QLabel(self.tab_8)
        self.label_99.setGeometry(QtCore.QRect(150, 180, 72, 15))
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.tab_8)
        self.label_100.setGeometry(QtCore.QRect(260, 180, 72, 15))
        self.label_100.setObjectName("label_100")
        self.label_101 = QtWidgets.QLabel(self.tab_8)
        self.label_101.setGeometry(QtCore.QRect(370, 180, 72, 15))
        self.label_101.setObjectName("label_101")
        self.label_102 = QtWidgets.QLabel(self.tab_8)
        self.label_102.setGeometry(QtCore.QRect(480, 180, 72, 15))
        self.label_102.setObjectName("label_102")
        self.label_103 = QtWidgets.QLabel(self.tab_8)
        self.label_103.setGeometry(QtCore.QRect(590, 180, 91, 16))
        self.label_103.setObjectName("label_103")
        self.lineEdit_79 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_79.setGeometry(QtCore.QRect(20, 210, 91, 21))
        self.lineEdit_79.setObjectName("lineEdit_79")
        self.lineEdit_80 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_80.setGeometry(QtCore.QRect(140, 210, 91, 21))
        self.lineEdit_80.setObjectName("lineEdit_80")
        self.lineEdit_81 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_81.setGeometry(QtCore.QRect(250, 210, 91, 21))
        self.lineEdit_81.setObjectName("lineEdit_81")
        self.lineEdit_82 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_82.setGeometry(QtCore.QRect(360, 210, 91, 21))
        self.lineEdit_82.setObjectName("lineEdit_82")
        self.lineEdit_83 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_83.setGeometry(QtCore.QRect(480, 210, 91, 21))
        self.lineEdit_83.setObjectName("lineEdit_83")
        self.lineEdit_84 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_84.setGeometry(QtCore.QRect(590, 210, 91, 21))
        self.lineEdit_84.setObjectName("lineEdit_84")
        self.label_104 = QtWidgets.QLabel(self.tab_8)
        self.label_104.setGeometry(QtCore.QRect(40, 270, 181, 16))
        self.label_104.setObjectName("label_104")
        self.comboBox_4 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_4.setGeometry(QtCore.QRect(230, 270, 211, 22))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_15 = QtWidgets.QLabel(self.tab_8)
        self.label_15.setGeometry(QtCore.QRect(470, 270, 111, 16))
        self.label_15.setObjectName("label_15")
        self.comboBox_5 = QtWidgets.QComboBox(self.tab_8)
        self.comboBox_5.setGeometry(QtCore.QRect(600, 270, 171, 22))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.label_39 = QtWidgets.QLabel(self.tab_8)
        self.label_39.setGeometry(QtCore.QRect(90, 340, 72, 15))
        self.label_39.setObjectName("label_39")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_9.setGeometry(QtCore.QRect(70, 360, 113, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.label_40 = QtWidgets.QLabel(self.tab_8)
        self.label_40.setGeometry(QtCore.QRect(260, 340, 101, 20))
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_8)
        self.label_41.setGeometry(QtCore.QRect(450, 340, 72, 15))
        self.label_41.setObjectName("label_41")
        self.lineEdit_31 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_31.setGeometry(QtCore.QRect(250, 360, 113, 21))
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.lineEdit_32 = QtWidgets.QLineEdit(self.tab_8)
        self.lineEdit_32.setGeometry(QtCore.QRect(430, 360, 113, 21))
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.pushButton_13 = QtWidgets.QPushButton(self.tab_8)
        self.pushButton_13.setGeometry(QtCore.QRect(370, 410, 93, 28))
        self.pushButton_13.setObjectName("pushButton_13")
        self.label_117 = QtWidgets.QLabel(self.tab_8)
        self.label_117.setGeometry(QtCore.QRect(70, 310, 611, 16))
        self.label_117.setObjectName("label_117")
        self.tabWidget_3.addTab(self.tab_8, "")
        self.tab_9 = QtWidgets.QWidget()
        self.tab_9.setObjectName("tab_9")
        self.label_42 = QtWidgets.QLabel(self.tab_9)
        self.label_42.setGeometry(QtCore.QRect(180, 70, 81, 16))
        self.label_42.setObjectName("label_42")
        self.pushButton_14 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_14.setGeometry(QtCore.QRect(40, 20, 93, 28))
        self.pushButton_14.setObjectName("pushButton_14")
        self.label_43 = QtWidgets.QLabel(self.tab_9)
        self.label_43.setGeometry(QtCore.QRect(161, 110, 91, 20))
        self.label_43.setObjectName("label_43")
        self.label_44 = QtWidgets.QLabel(self.tab_9)
        self.label_44.setGeometry(QtCore.QRect(161, 150, 91, 20))
        self.label_44.setObjectName("label_44")
        self.label_45 = QtWidgets.QLabel(self.tab_9)
        self.label_45.setGeometry(QtCore.QRect(180, 190, 72, 15))
        self.label_45.setObjectName("label_45")
        self.lineEdit_33 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_33.setGeometry(QtCore.QRect(270, 70, 113, 21))
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.lineEdit_34 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_34.setGeometry(QtCore.QRect(270, 110, 113, 21))
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.lineEdit_35 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_35.setGeometry(QtCore.QRect(270, 150, 113, 21))
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.lineEdit_36 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_36.setGeometry(QtCore.QRect(270, 190, 113, 21))
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.label_46 = QtWidgets.QLabel(self.tab_9)
        self.label_46.setGeometry(QtCore.QRect(470, 90, 72, 15))
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.tab_9)
        self.label_47.setGeometry(QtCore.QRect(470, 130, 72, 15))
        self.label_47.setObjectName("label_47")
        self.label_48 = QtWidgets.QLabel(self.tab_9)
        self.label_48.setGeometry(QtCore.QRect(470, 170, 72, 15))
        self.label_48.setObjectName("label_48")
        self.lineEdit_37 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_37.setGeometry(QtCore.QRect(540, 90, 113, 21))
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.lineEdit_38 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_38.setGeometry(QtCore.QRect(540, 130, 113, 21))
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.lineEdit_39 = QtWidgets.QLineEdit(self.tab_9)
        self.lineEdit_39.setGeometry(QtCore.QRect(540, 170, 113, 21))
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.pushButton_15 = QtWidgets.QPushButton(self.tab_9)
        self.pushButton_15.setGeometry(QtCore.QRect(380, 270, 93, 28))
        self.pushButton_15.setObjectName("pushButton_15")
        self.tabWidget_3.addTab(self.tab_9, "")
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.tabWidget_4 = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_4.setGeometry(QtCore.QRect(0, 0, 881, 521))
        self.tabWidget_4.setObjectName("tabWidget_4")
        self.tab_10 = QtWidgets.QWidget()
        self.tab_10.setObjectName("tab_10")
        self.pushButton_16 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_16.setGeometry(QtCore.QRect(40, 20, 93, 28))
        self.pushButton_16.setObjectName("pushButton_16")
        self.label_49 = QtWidgets.QLabel(self.tab_10)
        self.label_49.setGeometry(QtCore.QRect(251, 50, 91, 20))
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.tab_10)
        self.label_50.setGeometry(QtCore.QRect(280, 90, 72, 15))
        self.label_50.setObjectName("label_50")
        self.label_51 = QtWidgets.QLabel(self.tab_10)
        self.label_51.setGeometry(QtCore.QRect(251, 130, 91, 20))
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.tab_10)
        self.label_52.setGeometry(QtCore.QRect(251, 170, 91, 20))
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.tab_10)
        self.label_53.setGeometry(QtCore.QRect(251, 210, 91, 20))
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_10)
        self.label_54.setGeometry(QtCore.QRect(251, 250, 91, 20))
        self.label_54.setObjectName("label_54")
        self.label_55 = QtWidgets.QLabel(self.tab_10)
        self.label_55.setGeometry(QtCore.QRect(241, 300, 91, 20))
        self.label_55.setObjectName("label_55")
        self.label_56 = QtWidgets.QLabel(self.tab_10)
        self.label_56.setGeometry(QtCore.QRect(130, 340, 72, 15))
        self.label_56.setObjectName("label_56")
        self.label_57 = QtWidgets.QLabel(self.tab_10)
        self.label_57.setGeometry(QtCore.QRect(270, 340, 72, 15))
        self.label_57.setObjectName("label_57")
        self.label_58 = QtWidgets.QLabel(self.tab_10)
        self.label_58.setGeometry(QtCore.QRect(410, 340, 72, 15))
        self.label_58.setObjectName("label_58")
        self.label_59 = QtWidgets.QLabel(self.tab_10)
        self.label_59.setGeometry(QtCore.QRect(540, 340, 72, 15))
        self.label_59.setObjectName("label_59")
        self.lineEdit_40 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_40.setGeometry(QtCore.QRect(100, 370, 113, 21))
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_41.setGeometry(QtCore.QRect(250, 370, 113, 21))
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.lineEdit_42 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_42.setGeometry(QtCore.QRect(390, 370, 113, 21))
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.lineEdit_43 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_43.setGeometry(QtCore.QRect(530, 370, 113, 21))
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.lineEdit_44 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_44.setGeometry(QtCore.QRect(370, 50, 113, 21))
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.lineEdit_45 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_45.setGeometry(QtCore.QRect(370, 90, 221, 21))
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.lineEdit_46 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_46.setGeometry(QtCore.QRect(370, 130, 113, 21))
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.lineEdit_47 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_47.setGeometry(QtCore.QRect(370, 170, 113, 21))
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.lineEdit_48 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_48.setGeometry(QtCore.QRect(370, 210, 113, 21))
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.lineEdit_49 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_49.setGeometry(QtCore.QRect(370, 250, 113, 21))
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.lineEdit_50 = QtWidgets.QLineEdit(self.tab_10)
        self.lineEdit_50.setGeometry(QtCore.QRect(370, 300, 113, 21))
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.pushButton_30 = QtWidgets.QPushButton(self.tab_10)
        self.pushButton_30.setGeometry(QtCore.QRect(360, 420, 93, 28))
        self.pushButton_30.setObjectName("pushButton_30")
        self.tabWidget_4.addTab(self.tab_10, "")
        self.tab_11 = QtWidgets.QWidget()
        self.tab_11.setObjectName("tab_11")
        self.pushButton_17 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_17.setGeometry(QtCore.QRect(50, 30, 181, 28))
        self.pushButton_17.setObjectName("pushButton_17")
        self.label_60 = QtWidgets.QLabel(self.tab_11)
        self.label_60.setGeometry(QtCore.QRect(150, 70, 191, 16))
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_11)
        self.label_61.setGeometry(QtCore.QRect(110, 100, 72, 15))
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_11)
        self.label_62.setGeometry(QtCore.QRect(240, 100, 72, 15))
        self.label_62.setObjectName("label_62")
        self.label_63 = QtWidgets.QLabel(self.tab_11)
        self.label_63.setGeometry(QtCore.QRect(350, 100, 72, 15))
        self.label_63.setObjectName("label_63")
        self.lineEdit_51 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_51.setGeometry(QtCore.QRect(90, 120, 113, 21))
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.lineEdit_52 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_52.setGeometry(QtCore.QRect(210, 120, 113, 21))
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.lineEdit_53 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_53.setGeometry(QtCore.QRect(330, 120, 113, 21))
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.label_64 = QtWidgets.QLabel(self.tab_11)
        self.label_64.setGeometry(QtCore.QRect(110, 160, 72, 15))
        self.label_64.setObjectName("label_64")
        self.label_65 = QtWidgets.QLabel(self.tab_11)
        self.label_65.setGeometry(QtCore.QRect(230, 160, 72, 15))
        self.label_65.setObjectName("label_65")
        self.label_66 = QtWidgets.QLabel(self.tab_11)
        self.label_66.setGeometry(QtCore.QRect(340, 160, 72, 15))
        self.label_66.setObjectName("label_66")
        self.label_67 = QtWidgets.QLabel(self.tab_11)
        self.label_67.setGeometry(QtCore.QRect(460, 160, 72, 15))
        self.label_67.setObjectName("label_67")
        self.lineEdit_54 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_54.setGeometry(QtCore.QRect(80, 180, 113, 21))
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.lineEdit_55 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_55.setGeometry(QtCore.QRect(200, 180, 113, 21))
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.lineEdit_56 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_56.setGeometry(QtCore.QRect(320, 180, 113, 21))
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.lineEdit_57 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_57.setGeometry(QtCore.QRect(440, 180, 113, 21))
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.pushButton_18 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_18.setGeometry(QtCore.QRect(590, 170, 93, 28))
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_19.setGeometry(QtCore.QRect(50, 220, 181, 28))
        self.pushButton_19.setObjectName("pushButton_19")
        self.label_68 = QtWidgets.QLabel(self.tab_11)
        self.label_68.setGeometry(QtCore.QRect(150, 260, 191, 16))
        self.label_68.setObjectName("label_68")
        self.lineEdit_58 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_58.setGeometry(QtCore.QRect(80, 370, 113, 21))
        self.lineEdit_58.setObjectName("lineEdit_58")
        self.lineEdit_59 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_59.setGeometry(QtCore.QRect(440, 370, 113, 21))
        self.lineEdit_59.setObjectName("lineEdit_59")
        self.label_69 = QtWidgets.QLabel(self.tab_11)
        self.label_69.setGeometry(QtCore.QRect(260, 290, 72, 15))
        self.label_69.setObjectName("label_69")
        self.label_70 = QtWidgets.QLabel(self.tab_11)
        self.label_70.setGeometry(QtCore.QRect(110, 290, 72, 15))
        self.label_70.setObjectName("label_70")
        self.lineEdit_60 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_60.setGeometry(QtCore.QRect(200, 370, 113, 21))
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.lineEdit_73 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_73.setGeometry(QtCore.QRect(90, 310, 113, 21))
        self.lineEdit_73.setObjectName("lineEdit_73")
        self.label_71 = QtWidgets.QLabel(self.tab_11)
        self.label_71.setGeometry(QtCore.QRect(230, 350, 72, 15))
        self.label_71.setObjectName("label_71")
        self.lineEdit_74 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_74.setGeometry(QtCore.QRect(320, 370, 113, 21))
        self.lineEdit_74.setObjectName("lineEdit_74")
        self.lineEdit_75 = QtWidgets.QLineEdit(self.tab_11)
        self.lineEdit_75.setGeometry(QtCore.QRect(240, 310, 113, 21))
        self.lineEdit_75.setObjectName("lineEdit_75")
        self.label_72 = QtWidgets.QLabel(self.tab_11)
        self.label_72.setGeometry(QtCore.QRect(110, 350, 72, 15))
        self.label_72.setObjectName("label_72")
        self.label_73 = QtWidgets.QLabel(self.tab_11)
        self.label_73.setGeometry(QtCore.QRect(460, 350, 72, 15))
        self.label_73.setObjectName("label_73")
        self.label_74 = QtWidgets.QLabel(self.tab_11)
        self.label_74.setGeometry(QtCore.QRect(340, 350, 72, 15))
        self.label_74.setObjectName("label_74")
        self.pushButton_20 = QtWidgets.QPushButton(self.tab_11)
        self.pushButton_20.setGeometry(QtCore.QRect(590, 360, 93, 28))
        self.pushButton_20.setObjectName("pushButton_20")
        self.label_114 = QtWidgets.QLabel(self.tab_11)
        self.label_114.setGeometry(QtCore.QRect(540, 30, 171, 20))
        self.label_114.setObjectName("label_114")
        self.label_115 = QtWidgets.QLabel(self.tab_11)
        self.label_115.setGeometry(QtCore.QRect(480, 90, 391, 20))
        self.label_115.setObjectName("label_115")
        self.label_116 = QtWidgets.QLabel(self.tab_11)
        self.label_116.setGeometry(QtCore.QRect(520, 60, 241, 20))
        self.label_116.setObjectName("label_116")
        self.tabWidget_4.addTab(self.tab_11, "")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.label_75 = QtWidgets.QLabel(self.tab_4)
        self.label_75.setGeometry(QtCore.QRect(170, 40, 81, 16))
        self.label_75.setObjectName("label_75")
        self.pushButton_21 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_21.setGeometry(QtCore.QRect(30, 20, 101, 28))
        self.pushButton_21.setObjectName("pushButton_21")
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_3.setGeometry(QtCore.QRect(270, 40, 61, 19))
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_4.setGeometry(QtCore.QRect(350, 40, 61, 19))
        self.radioButton_4.setObjectName("radioButton_4")
        self.label_76 = QtWidgets.QLabel(self.tab_4)
        self.label_76.setGeometry(QtCore.QRect(120, 80, 72, 15))
        self.label_76.setObjectName("label_76")
        self.label_92 = QtWidgets.QLabel(self.tab_4)
        self.label_92.setGeometry(QtCore.QRect(120, 110, 72, 15))
        self.label_92.setObjectName("label_92")
        self.lineEdit_85 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_85.setGeometry(QtCore.QRect(200, 80, 113, 21))
        self.lineEdit_85.setObjectName("lineEdit_85")
        self.lineEdit_86 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_86.setGeometry(QtCore.QRect(200, 110, 113, 21))
        self.lineEdit_86.setObjectName("lineEdit_86")
        self.label_105 = QtWidgets.QLabel(self.tab_4)
        self.label_105.setGeometry(QtCore.QRect(390, 80, 72, 15))
        self.label_105.setObjectName("label_105")
        self.lineEdit_87 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_87.setGeometry(QtCore.QRect(470, 80, 113, 21))
        self.lineEdit_87.setObjectName("lineEdit_87")
        self.label_106 = QtWidgets.QLabel(self.tab_4)
        self.label_106.setGeometry(QtCore.QRect(100, 170, 72, 15))
        self.label_106.setObjectName("label_106")
        self.label_107 = QtWidgets.QLabel(self.tab_4)
        self.label_107.setGeometry(QtCore.QRect(140, 200, 71, 20))
        self.label_107.setObjectName("label_107")
        self.label_108 = QtWidgets.QLabel(self.tab_4)
        self.label_108.setGeometry(QtCore.QRect(130, 230, 81, 16))
        self.label_108.setObjectName("label_108")
        self.label_109 = QtWidgets.QLabel(self.tab_4)
        self.label_109.setGeometry(QtCore.QRect(100, 260, 111, 20))
        self.label_109.setObjectName("label_109")
        self.lineEdit_88 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_88.setGeometry(QtCore.QRect(220, 200, 113, 21))
        self.lineEdit_88.setObjectName("lineEdit_88")
        self.lineEdit_89 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_89.setGeometry(QtCore.QRect(220, 230, 113, 21))
        self.lineEdit_89.setObjectName("lineEdit_89")
        self.lineEdit_90 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_90.setGeometry(QtCore.QRect(220, 260, 113, 21))
        self.lineEdit_90.setObjectName("lineEdit_90")
        self.label_110 = QtWidgets.QLabel(self.tab_4)
        self.label_110.setGeometry(QtCore.QRect(390, 170, 72, 15))
        self.label_110.setObjectName("label_110")
        self.label_111 = QtWidgets.QLabel(self.tab_4)
        self.label_111.setGeometry(QtCore.QRect(420, 200, 72, 15))
        self.label_111.setObjectName("label_111")
        self.label_112 = QtWidgets.QLabel(self.tab_4)
        self.label_112.setGeometry(QtCore.QRect(420, 230, 72, 15))
        self.label_112.setObjectName("label_112")
        self.label_113 = QtWidgets.QLabel(self.tab_4)
        self.label_113.setGeometry(QtCore.QRect(430, 260, 41, 16))
        self.label_113.setObjectName("label_113")
        self.lineEdit_91 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_91.setGeometry(QtCore.QRect(500, 200, 113, 21))
        self.lineEdit_91.setObjectName("lineEdit_91")
        self.lineEdit_92 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_92.setGeometry(QtCore.QRect(500, 230, 113, 21))
        self.lineEdit_92.setObjectName("lineEdit_92")
        self.lineEdit_93 = QtWidgets.QLineEdit(self.tab_4)
        self.lineEdit_93.setGeometry(QtCore.QRect(500, 260, 113, 21))
        self.lineEdit_93.setObjectName("lineEdit_93")
        self.pushButton_22 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_22.setGeometry(QtCore.QRect(350, 340, 93, 28))
        self.pushButton_22.setObjectName("pushButton_22")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_12 = QtWidgets.QWidget()
        self.tab_12.setObjectName("tab_12")
        self.pushButton_23 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_23.setGeometry(QtCore.QRect(200, 110, 93, 28))
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.tab_12)
        self.pushButton_24.setGeometry(QtCore.QRect(510, 110, 93, 28))
        self.pushButton_24.setObjectName("pushButton_24")
        self.tabWidget.addTab(self.tab_12, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 901, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.tabWidget_2.setCurrentIndex(0)
        self.tabWidget_3.setCurrentIndex(2)
        self.tabWidget_4.setCurrentIndex(0)
        self.pushButton_2.clicked.connect(MainWindow.file1_save)
        self.pushButton_12.clicked.connect(MainWindow.file5_save)
        self.pushButton_28.clicked.connect(MainWindow.file2_save)
        self.pushButton_13.clicked.connect(MainWindow.file3_save)
        self.pushButton_15.clicked.connect(MainWindow.file6_save)
        self.pushButton_30.clicked.connect(MainWindow.file4_save)
        self.pushButton_18.clicked.connect(MainWindow.file9_save)
        self.pushButton_20.clicked.connect(MainWindow.file10_save)
        self.pushButton_22.clicked.connect(MainWindow.file7_8_save)
        self.pushButton_23.clicked.connect(MainWindow.combine_all_files)
        self.pushButton_24.clicked.connect(MainWindow.exit_data)
        self.pushButton.clicked.connect(MainWindow.load_file1)
        self.pushButton_26.clicked.connect(MainWindow.load_file2)
        self.pushButton_3.clicked.connect(MainWindow.load_file5)
        self.pushButton_25.clicked.connect(MainWindow.make_mesh)
        self.pushButton_29.clicked.connect(MainWindow.load_file3)
        self.pushButton_14.clicked.connect(MainWindow.load_file6)
        self.pushButton_16.clicked.connect(MainWindow.load_file4)
        self.pushButton_17.clicked.connect(MainWindow.load_file9)
        self.pushButton_19.clicked.connect(MainWindow.load_file10)
        self.pushButton_21.clicked.connect(MainWindow.load_file7_8)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "v0.1"))
        self.label.setText(_translate("MainWindow", "模型选择"))
        self.pushButton.setText(_translate("MainWindow", "从文件中读取"))
        self.comboBox.setItemText(0, _translate("MainWindow", "平衡"))
        self.comboBox.setItemText(1, _translate("MainWindow", "动力学"))
        self.label_2.setText(_translate("MainWindow", "组分"))
        self.label_3.setText(_translate("MainWindow", "方程"))
        self.label_4.setText(_translate("MainWindow", "相"))
        self.label_5.setText(_translate("MainWindow", "最大网格数"))
        self.label_6.setText(_translate("MainWindow", "最大连接数"))
        self.label_7.setText(_translate("MainWindow", "最大源汇项数"))
        self.label_8.setText(_translate("MainWindow", "最大介质数"))
        self.pushButton_2.setText(_translate("MainWindow", "保存"))
        self.label_9.setText(_translate("MainWindow", "组，方程，相"))
        self.label_10.setText(_translate("MainWindow", "（2,3,4）平衡，无抑制剂"))
        self.label_11.setText(_translate("MainWindow", "（3,4,4）平衡，有抑制剂"))
        self.label_12.setText(_translate("MainWindow", "（3,4,4）动力学，无抑制剂"))
        self.label_13.setText(_translate("MainWindow", "（4,5,4）动力学，有抑制剂"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("MainWindow", "EOS"))
        self.pushButton_3.setText(_translate("MainWindow", "从文件中读取"))
        self.radioButton.setText(_translate("MainWindow", "笛卡尔坐标"))
        self.radioButton_2.setText(_translate("MainWindow", "柱坐标"))
        self.label_14.setText(_translate("MainWindow", "最大网格数"))
        self.label_16.setText(_translate("MainWindow", "分区"))
        self.label_17.setText(_translate("MainWindow", "区域名称"))
        self.label_18.setText(_translate("MainWindow", "Xmin"))
        self.label_19.setText(_translate("MainWindow", "Xmax"))
        self.label_20.setText(_translate("MainWindow", "Ymin"))
        self.label_21.setText(_translate("MainWindow", "Ymax"))
        self.label_22.setText(_translate("MainWindow", "Zmin"))
        self.label_23.setText(_translate("MainWindow", "Zmax"))
        self.pushButton_4.setText(_translate("MainWindow", "添加"))
        self.pushButton_5.setText(_translate("MainWindow", "删除"))
        self.label_24.setText(_translate("MainWindow", "方向"))
        self.label_25.setText(_translate("MainWindow", "网格数"))
        self.label_26.setText(_translate("MainWindow", "网格长度"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "X"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Y"))
        self.comboBox_2.setItemText(2, _translate("MainWindow", "Z"))
        self.pushButton_6.setText(_translate("MainWindow", "添加"))
        self.pushButton_7.setText(_translate("MainWindow", "删除"))
        self.pushButton_8.setText(_translate("MainWindow", "添加"))
        self.label_27.setText(_translate("MainWindow", "Rmin"))
        self.label_28.setText(_translate("MainWindow", "最大网格数"))
        self.label_29.setText(_translate("MainWindow", "Rmax"))
        self.label_30.setText(_translate("MainWindow", "最大连接数"))
        self.label_31.setText(_translate("MainWindow", "Zmin"))
        self.label_32.setText(_translate("MainWindow", "区域名称"))
        self.pushButton_9.setText(_translate("MainWindow", "删除"))
        self.label_33.setText(_translate("MainWindow", "分区"))
        self.label_34.setText(_translate("MainWindow", "Zmax"))
        self.pushButton_10.setText(_translate("MainWindow", "删除"))
        self.label_35.setText(_translate("MainWindow", "方向"))
        self.pushButton_11.setText(_translate("MainWindow", "添加"))
        self.comboBox_3.setItemText(0, _translate("MainWindow", "R"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Z"))
        self.label_36.setText(_translate("MainWindow", "网格数"))
        self.label_37.setText(_translate("MainWindow", "网格长度"))
        self.label_38.setText(_translate("MainWindow", "分布形式"))
        self.pushButton_12.setText(_translate("MainWindow", "保存"))
        self.pushButton_25.setText(_translate("MainWindow", "生成网格"))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_6), _translate("MainWindow", "网格设计"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "模型状态"))
        self.pushButton_26.setText(_translate("MainWindow", "从文件中读取"))
        self.label_77.setText(_translate("MainWindow", "岩石名称"))
        self.label_78.setText(_translate("MainWindow", "NAD"))
        self.radioButton_5.setText(_translate("MainWindow", "1"))
        self.radioButton_6.setText(_translate("MainWindow", "0"))
        self.label_79.setText(_translate("MainWindow", "密度"))
        self.label_80.setText(_translate("MainWindow", "孔隙度"))
        self.label_81.setText(_translate("MainWindow", "I方向渗透率"))
        self.label_82.setText(_translate("MainWindow", "J方向渗透率"))
        self.label_83.setText(_translate("MainWindow", "K方向渗透率"))
        self.label_84.setText(_translate("MainWindow", "饱和流体导热系数"))
        self.label_85.setText(_translate("MainWindow", "比热容"))
        self.label_86.setText(_translate("MainWindow", "NAD=1 时输入"))
        self.label_87.setText(_translate("MainWindow", "孔隙压缩系数"))
        self.label_88.setText(_translate("MainWindow", "未饱和流体下"))
        self.label_89.setText(_translate("MainWindow", "地层导热系数"))
        self.label_90.setText(_translate("MainWindow", "临界孔隙度"))
        self.label_91.setText(_translate("MainWindow", "渗透率降低指数"))
        self.pushButton_27.setText(_translate("MainWindow", "添加"))
        self.pushButton_28.setText(_translate("MainWindow", "保存"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_7), _translate("MainWindow", "岩石"))
        self.pushButton_29.setText(_translate("MainWindow", "从文件中读取"))
        self.label_93.setText(_translate("MainWindow", "常数项"))
        self.label_94.setText(_translate("MainWindow", "导热系数多项式"))
        self.label_95.setText(_translate("MainWindow", "比热系数多项式"))
        self.label_96.setText(_translate("MainWindow", "水合物密度"))
        self.label_97.setText(_translate("MainWindow", "盐对相平衡条件的影响"))
        self.label_98.setText(_translate("MainWindow", "T_Maxoff"))
        self.label_99.setText(_translate("MainWindow", "C_Maxoff"))
        self.label_100.setText(_translate("MainWindow", "MW_Maxoff"))
        self.label_101.setText(_translate("MainWindow", "D_Inhib"))
        self.label_102.setText(_translate("MainWindow", "H_Inhsol"))
        self.label_103.setText(_translate("MainWindow", "Difco_Inhib"))
        self.label_104.setText(_translate("MainWindow", "描述P-T、△H-T方程选择"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Moridis"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Kamath"))
        self.comboBox_4.setItemText(2, _translate("MainWindow", "P-T Moridis,△H-T Kamath"))
        self.label_15.setText(_translate("MainWindow", "水合物分解模型"))
        self.comboBox_5.setItemText(0, _translate("MainWindow", "EQUILIBRIUM"))
        self.comboBox_5.setItemText(1, _translate("MainWindow", "KINETIC"))
        self.label_39.setText(_translate("MainWindow", "活化能"))
        self.label_40.setText(_translate("MainWindow", "固有速率常数"))
        self.label_41.setText(_translate("MainWindow", "表面因子"))
        self.pushButton_13.setText(_translate("MainWindow", "保存"))
        self.label_117.setText(_translate("MainWindow", "以下内容只在水合物分解模型选择了KINETIC时需要填写"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_8), _translate("MainWindow", "水合物"))
        self.label_42.setText(_translate("MainWindow", "相对渗透率"))
        self.pushButton_14.setText(_translate("MainWindow", "从文件中读取"))
        self.label_43.setText(_translate("MainWindow", "束缚水饱和度"))
        self.label_44.setText(_translate("MainWindow", "束缚气饱和度"))
        self.label_45.setText(_translate("MainWindow", "相渗系数"))
        self.label_46.setText(_translate("MainWindow", "毛管力"))
        self.label_47.setText(_translate("MainWindow", "参数η"))
        self.label_48.setText(_translate("MainWindow", "参数α"))
        self.pushButton_15.setText(_translate("MainWindow", "保存"))
        self.tabWidget_3.setTabText(self.tabWidget_3.indexOf(self.tab_9), _translate("MainWindow", "相对渗透率|毛管力"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "基本属性"))
        self.pushButton_16.setText(_translate("MainWindow", "从文件中读取"))
        self.label_49.setText(_translate("MainWindow", "收敛N次输出"))
        self.label_50.setText(_translate("MainWindow", "MOP"))
        self.label_51.setText(_translate("MainWindow", "模拟开始时间"))
        self.label_52.setText(_translate("MainWindow", "模拟结束时间"))
        self.label_53.setText(_translate("MainWindow", "最小时间步长"))
        self.label_54.setText(_translate("MainWindow", "最大时间步长"))
        self.label_55.setText(_translate("MainWindow", "模型初始状态"))
        self.label_56.setText(_translate("MainWindow", "第一主变量"))
        self.label_57.setText(_translate("MainWindow", "第二主变量"))
        self.label_58.setText(_translate("MainWindow", "第三主变量"))
        self.label_59.setText(_translate("MainWindow", "第四主变量"))
        self.pushButton_30.setText(_translate("MainWindow", "保存"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_10), _translate("MainWindow", "全局"))
        self.pushButton_17.setText(_translate("MainWindow", "打开文件来修改（INCON）"))
        self.label_60.setText(_translate("MainWindow", "更改部分网格条件（INCON）"))
        self.label_61.setText(_translate("MainWindow", "网格名称"))
        self.label_62.setText(_translate("MainWindow", "孔隙度"))
        self.label_63.setText(_translate("MainWindow", "初始状态"))
        self.label_64.setText(_translate("MainWindow", "主变量1"))
        self.label_65.setText(_translate("MainWindow", "主变量2"))
        self.label_66.setText(_translate("MainWindow", "主变量3"))
        self.label_67.setText(_translate("MainWindow", "主变量4"))
        self.pushButton_18.setText(_translate("MainWindow", "添加并保存"))
        self.pushButton_19.setText(_translate("MainWindow", "打开文件来修改（INDOM）"))
        self.label_68.setText(_translate("MainWindow", "更改部分网格条件（INDOM）"))
        self.label_69.setText(_translate("MainWindow", "初始状态"))
        self.label_70.setText(_translate("MainWindow", "网格名称"))
        self.label_71.setText(_translate("MainWindow", "主变量2"))
        self.label_72.setText(_translate("MainWindow", "主变量1"))
        self.label_73.setText(_translate("MainWindow", "主变量4"))
        self.label_74.setText(_translate("MainWindow", "主变量3"))
        self.pushButton_20.setText(_translate("MainWindow", "添加并保存"))
        self.label_114.setText(_translate("MainWindow", "注意：此部分非必须填写"))
        self.label_115.setText(_translate("MainWindow", "即使留空，也请依次点击下方两个保存按钮以生成空文件"))
        self.label_116.setText(_translate("MainWindow", "但程序最终合成文件需这部分的文件"))
        self.tabWidget_4.setTabText(self.tabWidget_4.indexOf(self.tab_11), _translate("MainWindow", "更改部分"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "初始条件"))
        self.label_75.setText(_translate("MainWindow", "源汇项类型"))
        self.pushButton_21.setText(_translate("MainWindow", "从文件中读取"))
        self.radioButton_3.setText(_translate("MainWindow", "pro"))
        self.radioButton_4.setText(_translate("MainWindow", "inj"))
        self.label_76.setText(_translate("MainWindow", "名称"))
        self.label_92.setText(_translate("MainWindow", "井号编码"))
        self.label_105.setText(_translate("MainWindow", "界面流动"))
        self.label_106.setText(_translate("MainWindow", "生产井"))
        self.label_107.setText(_translate("MainWindow", "生产方式"))
        self.label_108.setText(_translate("MainWindow", "生产井指数"))
        self.label_109.setText(_translate("MainWindow", "生产井井底压力"))
        self.label_110.setText(_translate("MainWindow", "注入井"))
        self.label_111.setText(_translate("MainWindow", "注入方式"))
        self.label_112.setText(_translate("MainWindow", "注入速率"))
        self.label_113.setText(_translate("MainWindow", "热焓"))
        self.pushButton_22.setText(_translate("MainWindow", "保存"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "生产设置"))
        self.pushButton_23.setText(_translate("MainWindow", "合成输入文件"))
        self.pushButton_24.setText(_translate("MainWindow", "退出"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_12), _translate("MainWindow", "文件合成"))
